---
title: Laura Jane Coulson
timezone: UTC
collections:
  commissions:
    title: Commissions
    output: true
  editorial:
    title: Editorial
    output: true
  moving-image:
    title: Moving Image
    output: true
  personal:
    title: Personal
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.laurajanecoulson.com
description: London-based photographer and filmmaker
permalink: pretty
exclude:
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
email: hello@laurajanecoulson.com
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %Y"
future: true
social:
  instagram: https://www.instagram.com/laurajanecoulson/
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  collection: posts
  enabled: true
  per_page: 12
  limit: 0
  permalink: "/page/:num/"
  title: ":title"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: false
imgix:
  source: laura-jane-coulson.imgix.net
